//! Linux syscall NAME -> ABI-specific number tables.
//! Extracted verbatim from the seccomp compiler for the <=400-LOC godfile
//! invariant (behavior-preserving). Consumed by `super::compile`.

/// Resolve a Linux syscall NAME → its x86_64 number via the `libc::SYS_*`
/// constants (so the numbers are target-correct). Covers the full set named by
/// the Docker default seccomp profile plus the common remainder; an unknown name
/// returns `None` so the caller fails closed. The `libc::SYS_*` constants are
/// `i64`, returned as such for the BPF `k` cast.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[allow(dead_code)] // Target build constructs only its own ABI variant.
pub(super) enum SeccompArch {
    X86_64,
    Aarch64,
}

pub(super) const fn target_arch() -> SeccompArch {
    #[cfg(target_arch = "x86_64")]
    {
        SeccompArch::X86_64
    }
    #[cfg(target_arch = "aarch64")]
    {
        SeccompArch::Aarch64
    }
}

pub(super) fn syscall_nr(name: &str) -> Option<i64> {
    #[cfg(target_arch = "x86_64")]
    {
        x86_64_syscall_nr(name)
    }
    #[cfg(target_arch = "aarch64")]
    {
        aarch64_syscall_nr(name)
    }
}

#[cfg(test)]
pub(super) fn syscall_nr_for_arch(name: &str, arch: SeccompArch) -> Option<i64> {
    match arch {
        SeccompArch::X86_64 => x86_64_test_nr(name),
        SeccompArch::Aarch64 => aarch64_syscall_nr(name),
    }
}

#[cfg(target_arch = "x86_64")]
fn x86_64_syscall_nr(name: &str) -> Option<i64> {
    Some(match name {
        "accept" => libc::SYS_accept,
        "accept4" => libc::SYS_accept4,
        "access" => libc::SYS_access,
        "adjtimex" => libc::SYS_adjtimex,
        "alarm" => libc::SYS_alarm,
        // x86_64 nr 158 — glibc/musl TLS setup calls this in every program's
        // startup (ARCH_SET_FS); REQUIRED for the `default` allow-list or the C
        // runtime traps before `main`. Added for the built-in profile (WP-#111+).
        "arch_prctl" => libc::SYS_arch_prctl,
        "bind" => libc::SYS_bind,
        "brk" => libc::SYS_brk,
        "capget" => libc::SYS_capget,
        "capset" => libc::SYS_capset,
        "chdir" => libc::SYS_chdir,
        "chmod" => libc::SYS_chmod,
        "chown" => libc::SYS_chown,
        "chroot" => libc::SYS_chroot,
        "clock_adjtime" => libc::SYS_clock_adjtime,
        "clock_getres" => libc::SYS_clock_getres,
        "clock_gettime" => libc::SYS_clock_gettime,
        "clock_nanosleep" => libc::SYS_clock_nanosleep,
        "clone" => libc::SYS_clone,
        "clone3" => libc::SYS_clone3,
        "close" => libc::SYS_close,
        "close_range" => libc::SYS_close_range,
        "connect" => libc::SYS_connect,
        "copy_file_range" => libc::SYS_copy_file_range,
        "creat" => libc::SYS_creat,
        "dup" => libc::SYS_dup,
        "dup2" => libc::SYS_dup2,
        "dup3" => libc::SYS_dup3,
        "epoll_create" => libc::SYS_epoll_create,
        "epoll_create1" => libc::SYS_epoll_create1,
        "epoll_ctl" => libc::SYS_epoll_ctl,
        "epoll_ctl_old" => libc::SYS_epoll_ctl_old,
        "epoll_pwait" => libc::SYS_epoll_pwait,
        "epoll_pwait2" => libc::SYS_epoll_pwait2,
        "epoll_wait" => libc::SYS_epoll_wait,
        "epoll_wait_old" => libc::SYS_epoll_wait_old,
        "eventfd" => libc::SYS_eventfd,
        "eventfd2" => libc::SYS_eventfd2,
        "execve" => libc::SYS_execve,
        "execveat" => libc::SYS_execveat,
        "exit" => libc::SYS_exit,
        "exit_group" => libc::SYS_exit_group,
        "faccessat" => libc::SYS_faccessat,
        "faccessat2" => libc::SYS_faccessat2,
        "fadvise64" => libc::SYS_fadvise64,
        "fallocate" => libc::SYS_fallocate,
        "fanotify_mark" => libc::SYS_fanotify_mark,
        "fchdir" => libc::SYS_fchdir,
        "fchmod" => libc::SYS_fchmod,
        "fchmodat" => libc::SYS_fchmodat,
        "fchown" => libc::SYS_fchown,
        "fchownat" => libc::SYS_fchownat,
        "fcntl" => libc::SYS_fcntl,
        "fdatasync" => libc::SYS_fdatasync,
        "fgetxattr" => libc::SYS_fgetxattr,
        "flistxattr" => libc::SYS_flistxattr,
        "flock" => libc::SYS_flock,
        "fork" => libc::SYS_fork,
        "fremovexattr" => libc::SYS_fremovexattr,
        "fsetxattr" => libc::SYS_fsetxattr,
        "fstat" => libc::SYS_fstat,
        "fstatfs" => libc::SYS_fstatfs,
        "fsync" => libc::SYS_fsync,
        "ftruncate" => libc::SYS_ftruncate,
        "futex" => libc::SYS_futex,
        "futex_waitv" => libc::SYS_futex_waitv,
        "futimesat" => libc::SYS_futimesat,
        "getcpu" => libc::SYS_getcpu,
        "getcwd" => libc::SYS_getcwd,
        "getdents" => libc::SYS_getdents,
        "getdents64" => libc::SYS_getdents64,
        "getegid" => libc::SYS_getegid,
        "geteuid" => libc::SYS_geteuid,
        "getgid" => libc::SYS_getgid,
        "getgroups" => libc::SYS_getgroups,
        "getitimer" => libc::SYS_getitimer,
        "getpeername" => libc::SYS_getpeername,
        "getpgid" => libc::SYS_getpgid,
        "getpgrp" => libc::SYS_getpgrp,
        "getpid" => libc::SYS_getpid,
        "getppid" => libc::SYS_getppid,
        "getpriority" => libc::SYS_getpriority,
        "get_robust_list" => libc::SYS_get_robust_list,
        "getrandom" => libc::SYS_getrandom,
        "getresgid" => libc::SYS_getresgid,
        "getresuid" => libc::SYS_getresuid,
        "getrlimit" => libc::SYS_getrlimit,
        "getrusage" => libc::SYS_getrusage,
        "getsid" => libc::SYS_getsid,
        "getsockname" => libc::SYS_getsockname,
        "getsockopt" => libc::SYS_getsockopt,
        "gettid" => libc::SYS_gettid,
        "gettimeofday" => libc::SYS_gettimeofday,
        "getuid" => libc::SYS_getuid,
        "getxattr" => libc::SYS_getxattr,
        "inotify_add_watch" => libc::SYS_inotify_add_watch,
        "inotify_init" => libc::SYS_inotify_init,
        "inotify_init1" => libc::SYS_inotify_init1,
        "inotify_rm_watch" => libc::SYS_inotify_rm_watch,
        "io_cancel" => libc::SYS_io_cancel,
        "io_destroy" => libc::SYS_io_destroy,
        "io_getevents" => libc::SYS_io_getevents,
        // NOTE: `io_pgetevents` (x86_64 nr 333) is absent from the pinned libc
        // (0.2.186) `SYS_*` set, so it is intentionally omitted — an unknown name
        // fails closed (the safety net), which is the correct conservative behavior
        // for a profile that lists it (it is not in the Docker default's hot path).
        "io_setup" => libc::SYS_io_setup,
        "io_submit" => libc::SYS_io_submit,
        "io_uring_enter" => libc::SYS_io_uring_enter,
        "io_uring_register" => libc::SYS_io_uring_register,
        "io_uring_setup" => libc::SYS_io_uring_setup,
        "ioctl" => libc::SYS_ioctl,
        "ioprio_get" => libc::SYS_ioprio_get,
        "ioprio_set" => libc::SYS_ioprio_set,
        "kcmp" => libc::SYS_kcmp,
        "keyctl" => libc::SYS_keyctl,
        "kill" => libc::SYS_kill,
        "landlock_add_rule" => libc::SYS_landlock_add_rule,
        "landlock_create_ruleset" => libc::SYS_landlock_create_ruleset,
        "landlock_restrict_self" => libc::SYS_landlock_restrict_self,
        "lchown" => libc::SYS_lchown,
        "lgetxattr" => libc::SYS_lgetxattr,
        "link" => libc::SYS_link,
        "linkat" => libc::SYS_linkat,
        "listen" => libc::SYS_listen,
        "listxattr" => libc::SYS_listxattr,
        "llistxattr" => libc::SYS_llistxattr,
        "lremovexattr" => libc::SYS_lremovexattr,
        "lseek" => libc::SYS_lseek,
        "lsetxattr" => libc::SYS_lsetxattr,
        "lstat" => libc::SYS_lstat,
        "madvise" => libc::SYS_madvise,
        "mbind" => libc::SYS_mbind,
        "membarrier" => libc::SYS_membarrier,
        "memfd_create" => libc::SYS_memfd_create,
        "mincore" => libc::SYS_mincore,
        "mkdir" => libc::SYS_mkdir,
        "mkdirat" => libc::SYS_mkdirat,
        "mknod" => libc::SYS_mknod,
        "mknodat" => libc::SYS_mknodat,
        "mlock" => libc::SYS_mlock,
        "mlock2" => libc::SYS_mlock2,
        "mlockall" => libc::SYS_mlockall,
        "mmap" => libc::SYS_mmap,
        "mount" => libc::SYS_mount,
        "move_mount" => libc::SYS_move_mount,
        "mprotect" => libc::SYS_mprotect,
        "mq_getsetattr" => libc::SYS_mq_getsetattr,
        "mq_notify" => libc::SYS_mq_notify,
        "mq_open" => libc::SYS_mq_open,
        "mq_timedreceive" => libc::SYS_mq_timedreceive,
        "mq_timedsend" => libc::SYS_mq_timedsend,
        "mq_unlink" => libc::SYS_mq_unlink,
        "mremap" => libc::SYS_mremap,
        "msgctl" => libc::SYS_msgctl,
        "msgget" => libc::SYS_msgget,
        "msgrcv" => libc::SYS_msgrcv,
        "msgsnd" => libc::SYS_msgsnd,
        "msync" => libc::SYS_msync,
        "munlock" => libc::SYS_munlock,
        "munlockall" => libc::SYS_munlockall,
        "munmap" => libc::SYS_munmap,
        "name_to_handle_at" => libc::SYS_name_to_handle_at,
        "nanosleep" => libc::SYS_nanosleep,
        "newfstatat" => libc::SYS_newfstatat,
        "open" => libc::SYS_open,
        "openat" => libc::SYS_openat,
        "openat2" => libc::SYS_openat2,
        "pause" => libc::SYS_pause,
        "personality" => libc::SYS_personality,
        "pidfd_getfd" => libc::SYS_pidfd_getfd,
        "pidfd_open" => libc::SYS_pidfd_open,
        "pidfd_send_signal" => libc::SYS_pidfd_send_signal,
        "pipe" => libc::SYS_pipe,
        "pipe2" => libc::SYS_pipe2,
        "pivot_root" => libc::SYS_pivot_root,
        "pkey_alloc" => libc::SYS_pkey_alloc,
        "pkey_free" => libc::SYS_pkey_free,
        "pkey_mprotect" => libc::SYS_pkey_mprotect,
        "poll" => libc::SYS_poll,
        "ppoll" => libc::SYS_ppoll,
        "prctl" => libc::SYS_prctl,
        "pread64" => libc::SYS_pread64,
        "preadv" => libc::SYS_preadv,
        "preadv2" => libc::SYS_preadv2,
        "prlimit64" => libc::SYS_prlimit64,
        "process_madvise" => libc::SYS_process_madvise,
        "process_mrelease" => libc::SYS_process_mrelease,
        "process_vm_readv" => libc::SYS_process_vm_readv,
        "process_vm_writev" => libc::SYS_process_vm_writev,
        "pselect6" => libc::SYS_pselect6,
        "ptrace" => libc::SYS_ptrace,
        "pwrite64" => libc::SYS_pwrite64,
        "pwritev" => libc::SYS_pwritev,
        "pwritev2" => libc::SYS_pwritev2,
        "read" => libc::SYS_read,
        "readahead" => libc::SYS_readahead,
        "readlink" => libc::SYS_readlink,
        "readlinkat" => libc::SYS_readlinkat,
        "readv" => libc::SYS_readv,
        "reboot" => libc::SYS_reboot,
        "recvfrom" => libc::SYS_recvfrom,
        "recvmmsg" => libc::SYS_recvmmsg,
        "recvmsg" => libc::SYS_recvmsg,
        "remap_file_pages" => libc::SYS_remap_file_pages,
        "removexattr" => libc::SYS_removexattr,
        "rename" => libc::SYS_rename,
        "renameat" => libc::SYS_renameat,
        "renameat2" => libc::SYS_renameat2,
        "restart_syscall" => libc::SYS_restart_syscall,
        "rmdir" => libc::SYS_rmdir,
        "rseq" => libc::SYS_rseq,
        "rt_sigaction" => libc::SYS_rt_sigaction,
        "rt_sigpending" => libc::SYS_rt_sigpending,
        "rt_sigprocmask" => libc::SYS_rt_sigprocmask,
        "rt_sigqueueinfo" => libc::SYS_rt_sigqueueinfo,
        "rt_sigreturn" => libc::SYS_rt_sigreturn,
        "rt_sigsuspend" => libc::SYS_rt_sigsuspend,
        "rt_sigtimedwait" => libc::SYS_rt_sigtimedwait,
        "rt_tgsigqueueinfo" => libc::SYS_rt_tgsigqueueinfo,
        "sched_get_priority_max" => libc::SYS_sched_get_priority_max,
        "sched_get_priority_min" => libc::SYS_sched_get_priority_min,
        "sched_getaffinity" => libc::SYS_sched_getaffinity,
        "sched_getattr" => libc::SYS_sched_getattr,
        "sched_getparam" => libc::SYS_sched_getparam,
        "sched_getscheduler" => libc::SYS_sched_getscheduler,
        "sched_rr_get_interval" => libc::SYS_sched_rr_get_interval,
        "sched_setaffinity" => libc::SYS_sched_setaffinity,
        "sched_setattr" => libc::SYS_sched_setattr,
        "sched_setparam" => libc::SYS_sched_setparam,
        "sched_setscheduler" => libc::SYS_sched_setscheduler,
        "sched_yield" => libc::SYS_sched_yield,
        "seccomp" => libc::SYS_seccomp,
        "select" => libc::SYS_select,
        "semctl" => libc::SYS_semctl,
        "semget" => libc::SYS_semget,
        "semop" => libc::SYS_semop,
        "semtimedop" => libc::SYS_semtimedop,
        "sendfile" => libc::SYS_sendfile,
        "sendmmsg" => libc::SYS_sendmmsg,
        "sendmsg" => libc::SYS_sendmsg,
        "sendto" => libc::SYS_sendto,
        "set_robust_list" => libc::SYS_set_robust_list,
        "set_tid_address" => libc::SYS_set_tid_address,
        "setfsgid" => libc::SYS_setfsgid,
        "setfsuid" => libc::SYS_setfsuid,
        "setgid" => libc::SYS_setgid,
        "setgroups" => libc::SYS_setgroups,
        "setitimer" => libc::SYS_setitimer,
        "setns" => libc::SYS_setns,
        "setpgid" => libc::SYS_setpgid,
        "setpriority" => libc::SYS_setpriority,
        "setregid" => libc::SYS_setregid,
        "setresgid" => libc::SYS_setresgid,
        "setresuid" => libc::SYS_setresuid,
        "setreuid" => libc::SYS_setreuid,
        "setrlimit" => libc::SYS_setrlimit,
        "setsid" => libc::SYS_setsid,
        "setsockopt" => libc::SYS_setsockopt,
        "settimeofday" => libc::SYS_settimeofday,
        "setuid" => libc::SYS_setuid,
        "setxattr" => libc::SYS_setxattr,
        "shmat" => libc::SYS_shmat,
        "shmctl" => libc::SYS_shmctl,
        "shmdt" => libc::SYS_shmdt,
        "shmget" => libc::SYS_shmget,
        "shutdown" => libc::SYS_shutdown,
        "sigaltstack" => libc::SYS_sigaltstack,
        "signalfd" => libc::SYS_signalfd,
        "signalfd4" => libc::SYS_signalfd4,
        "socket" => libc::SYS_socket,
        "socketpair" => libc::SYS_socketpair,
        "splice" => libc::SYS_splice,
        "stat" => libc::SYS_stat,
        "statfs" => libc::SYS_statfs,
        "statx" => libc::SYS_statx,
        "symlink" => libc::SYS_symlink,
        "symlinkat" => libc::SYS_symlinkat,
        "sync" => libc::SYS_sync,
        "sync_file_range" => libc::SYS_sync_file_range,
        "syncfs" => libc::SYS_syncfs,
        "sysinfo" => libc::SYS_sysinfo,
        "syslog" => libc::SYS_syslog,
        "tee" => libc::SYS_tee,
        "tgkill" => libc::SYS_tgkill,
        "time" => libc::SYS_time,
        "timer_create" => libc::SYS_timer_create,
        "timer_delete" => libc::SYS_timer_delete,
        "timer_getoverrun" => libc::SYS_timer_getoverrun,
        "timer_gettime" => libc::SYS_timer_gettime,
        "timer_settime" => libc::SYS_timer_settime,
        "timerfd_create" => libc::SYS_timerfd_create,
        "timerfd_gettime" => libc::SYS_timerfd_gettime,
        "timerfd_settime" => libc::SYS_timerfd_settime,
        "times" => libc::SYS_times,
        "tkill" => libc::SYS_tkill,
        "truncate" => libc::SYS_truncate,
        "umask" => libc::SYS_umask,
        "uname" => libc::SYS_uname,
        "unlink" => libc::SYS_unlink,
        "unlinkat" => libc::SYS_unlinkat,
        "utime" => libc::SYS_utime,
        "utimensat" => libc::SYS_utimensat,
        "utimes" => libc::SYS_utimes,
        "vfork" => libc::SYS_vfork,
        "vmsplice" => libc::SYS_vmsplice,
        "wait4" => libc::SYS_wait4,
        "waitid" => libc::SYS_waitid,
        "write" => libc::SYS_write,
        "writev" => libc::SYS_writev,
        _ => return None,
    })
}

#[cfg(test)]
fn x86_64_test_nr(name: &str) -> Option<i64> {
    #[cfg(target_arch = "x86_64")]
    {
        x86_64_syscall_nr(name)
    }
    #[cfg(target_arch = "aarch64")]
    {
        Some(match name {
            "read" => 0,
            "write" => 1,
            "mkdirat" => 258,
            _ => return None,
        })
    }
}

// AArch64 Linux uses the asm-generic syscall ABI. Keep this table separate from
// x86_64: same names frequently have different numbers, and x86-only names must
// remain unsupported rather than map to an unrelated syscall.
#[allow(dead_code)] // x86_64 builds select their own table.
fn aarch64_syscall_nr(name: &str) -> Option<i64> {
    Some(match name {
        "accept" => 202,
        "accept4" => 242,
        "adjtimex" => 171,
        "bind" => 200,
        "brk" => 214,
        "capget" => 90,
        "capset" => 91,
        "chdir" => 49,
        "clock_adjtime" => 266,
        "clock_getres" => 114,
        "clock_gettime" => 113,
        "clock_nanosleep" => 115,
        "clone" => 220,
        "clone3" => 435,
        "close" => 57,
        "close_range" => 436,
        "connect" => 203,
        "copy_file_range" => 285,
        "dup" => 23,
        "dup3" => 24,
        "epoll_create1" => 20,
        "epoll_ctl" => 21,
        "epoll_pwait" => 22,
        "epoll_pwait2" => 441,
        "eventfd2" => 19,
        "execve" => 221,
        "execveat" => 281,
        "exit" => 93,
        "exit_group" => 94,
        "faccessat" => 48,
        "faccessat2" => 439,
        "fallocate" => 47,
        "fanotify_mark" => 263,
        "fchdir" => 50,
        "fchmod" => 52,
        "fchmodat" => 53,
        "fchown" => 55,
        "fchownat" => 54,
        "fcntl" => 25,
        "fdatasync" => 83,
        "fgetxattr" => 10,
        "flistxattr" => 13,
        "flock" => 32,
        "fremovexattr" => 16,
        "fsetxattr" => 7,
        "fstat" => 80,
        "fstatfs" => 44,
        "fsync" => 82,
        "ftruncate" => 46,
        "futex" => 98,
        "futex_waitv" => 449,
        "get_robust_list" => 100,
        "getcpu" => 168,
        "getcwd" => 17,
        "getdents64" => 61,
        "getegid" => 177,
        "geteuid" => 175,
        "getgid" => 176,
        "getgroups" => 158,
        "getitimer" => 102,
        "getpeername" => 205,
        "getpgid" => 155,
        "getpid" => 172,
        "getppid" => 173,
        "getpriority" => 141,
        "getrandom" => 278,
        "getresgid" => 150,
        "getresuid" => 148,
        "getrusage" => 165,
        "getsid" => 156,
        "getsockname" => 204,
        "getsockopt" => 209,
        "gettid" => 178,
        "gettimeofday" => 169,
        "getuid" => 174,
        "getxattr" => 8,
        "inotify_add_watch" => 27,
        "inotify_init1" => 26,
        "inotify_rm_watch" => 28,
        "io_cancel" => 3,
        "io_destroy" => 1,
        "io_getevents" => 4,
        "io_setup" => 0,
        "io_submit" => 2,
        "ioctl" => 29,
        "ioprio_get" => 31,
        "ioprio_set" => 30,
        "kcmp" => 272,
        "keyctl" => 219,
        "kill" => 129,
        "landlock_add_rule" => 445,
        "landlock_create_ruleset" => 444,
        "landlock_restrict_self" => 446,
        "lgetxattr" => 9,
        "linkat" => 37,
        "listen" => 201,
        "listxattr" => 11,
        "llistxattr" => 12,
        "lremovexattr" => 15,
        "lseek" => 62,
        "lsetxattr" => 6,
        "madvise" => 233,
        "mbind" => 235,
        "membarrier" => 283,
        "memfd_create" => 279,
        "mincore" => 232,
        "mkdirat" => 34,
        "mknodat" => 33,
        "mlock" => 228,
        "mlock2" => 284,
        "mlockall" => 230,
        "mmap" => 222,
        "mprotect" => 226,
        "mq_getsetattr" => 185,
        "mq_notify" => 184,
        "mq_open" => 180,
        "mq_timedreceive" => 183,
        "mq_timedsend" => 182,
        "mq_unlink" => 181,
        "mremap" => 216,
        "msgctl" => 187,
        "msgget" => 186,
        "msgrcv" => 188,
        "msgsnd" => 189,
        "msync" => 227,
        "munlock" => 229,
        "munlockall" => 231,
        "munmap" => 215,
        "name_to_handle_at" => 264,
        "nanosleep" => 101,
        "newfstatat" => 79,
        "openat" => 56,
        "openat2" => 437,
        "pidfd_open" => 434,
        "pidfd_send_signal" => 424,
        "pipe2" => 59,
        "pkey_alloc" => 289,
        "pkey_free" => 290,
        "pkey_mprotect" => 288,
        "ppoll" => 73,
        "prctl" => 167,
        "pread64" => 67,
        "preadv" => 69,
        "preadv2" => 286,
        "prlimit64" => 261,
        "process_madvise" => 440,
        "process_mrelease" => 448,
        "process_vm_readv" => 270,
        "process_vm_writev" => 271,
        "pselect6" => 72,
        "ptrace" => 117,
        "pwrite64" => 68,
        "pwritev" => 70,
        "pwritev2" => 287,
        "read" => 63,
        "readahead" => 213,
        "readlinkat" => 78,
        "readv" => 65,
        "reboot" => 142,
        "recvfrom" => 207,
        "recvmmsg" => 243,
        "recvmsg" => 212,
        "remap_file_pages" => 234,
        "removexattr" => 14,
        "renameat2" => 276,
        "restart_syscall" => 128,
        "rseq" => 293,
        "rt_sigaction" => 134,
        "rt_sigpending" => 136,
        "rt_sigprocmask" => 135,
        "rt_sigqueueinfo" => 138,
        "rt_sigreturn" => 139,
        "rt_sigsuspend" => 133,
        "rt_sigtimedwait" => 137,
        "rt_tgsigqueueinfo" => 240,
        "sched_get_priority_max" => 125,
        "sched_get_priority_min" => 126,
        "sched_getaffinity" => 123,
        "sched_getattr" => 275,
        "sched_getparam" => 121,
        "sched_getscheduler" => 120,
        "sched_rr_get_interval" => 127,
        "sched_setaffinity" => 122,
        "sched_setattr" => 274,
        "sched_setparam" => 118,
        "sched_setscheduler" => 119,
        "sched_yield" => 124,
        "seccomp" => 277,
        "semctl" => 191,
        "semget" => 190,
        "semop" => 193,
        "semtimedop" => 192,
        "sendmmsg" => 269,
        "sendmsg" => 211,
        "sendto" => 206,
        "set_robust_list" => 99,
        "set_tid_address" => 96,
        "setfsgid" => 152,
        "setfsuid" => 151,
        "setgid" => 144,
        "setgroups" => 159,
        "setitimer" => 103,
        "setns" => 268,
        "setpgid" => 154,
        "setpriority" => 140,
        "setregid" => 143,
        "setresgid" => 149,
        "setresuid" => 147,
        "setreuid" => 145,
        "setsid" => 157,
        "setsockopt" => 208,
        "settimeofday" => 170,
        "setuid" => 146,
        "setxattr" => 5,
        "shmat" => 196,
        "shmctl" => 195,
        "shmdt" => 197,
        "shmget" => 194,
        "shutdown" => 210,
        "sigaltstack" => 132,
        "signalfd4" => 74,
        "socket" => 198,
        "socketpair" => 199,
        "splice" => 76,
        "statfs" => 43,
        "statx" => 291,
        "symlinkat" => 36,
        "sync" => 81,
        "syncfs" => 267,
        "sysinfo" => 179,
        "syslog" => 116,
        "tee" => 77,
        "tgkill" => 131,
        "timer_create" => 107,
        "timer_delete" => 111,
        "timer_getoverrun" => 109,
        "timer_gettime" => 108,
        "timer_settime" => 110,
        "timerfd_create" => 85,
        "timerfd_gettime" => 87,
        "timerfd_settime" => 86,
        "times" => 153,
        "tkill" => 130,
        "truncate" => 45,
        "umask" => 166,
        "uname" => 160,
        "unlinkat" => 35,
        "utimensat" => 88,
        "vmsplice" => 75,
        "wait4" => 260,
        "waitid" => 95,
        "write" => 64,
        "writev" => 66,
        _ => return None,
    })
}
